# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Kamailio Toolchain

on:
  push:
    branches: [ "otter"]
    paths:
      - 'packages/server/kamailio/**'
      - '.github/workflows/kamailio.yml'
  pull_request:
  release:
    types: [created, edited]

permissions:
  contents: read

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/openline-kamailio-server


jobs:
    test:
      name: "Run Kamailio Unit Tests"
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          if [ -f packages/server/kamailio/requirements.txt ]; then pip install -r packages/server/kamailio/requirements.txt; fi
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          cd packages/server/kamailio/test
          python3 -m unittest discover
